# YML file for setting up a virtual environment including packages used for processing point clouds, GIS and raster to produce raster using spyder.

name: geofabrics
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - gdal=3.2.2 # pin to ensure consistent grid alignment PDAL writers.gdal
  - geopandas
  - requests
  - boto3
  - rioxarray
  - pdal=2.2
  - python-pdal=2.4=py38h1fd1430_1 # pin version so compatible with PDAL 2.2 but for Linux
  - python-dotenv
  - matplotlib
  - ipykernel
  - ipython
  - ipython_genutils
  - jupyter_client
  - jupyter_core
  - pytest
  - spyder
  - spyder-kernels
  - pip:
    - geoapis==0.1.0

prefix: C:\ProgramData\Anaconda3\envs\geofabrics
