# YML file for setting up a virtual environment including packages used for processing point clouds, GIS and raster to produce raster using spyder.

name: geofabrics
channels:
  - conda-forge
  - defaults
dependencies:
  - pyproj
  - pip
  - gdal
  - geopandas >=0.10.2
  - rioxarray
  - pdal
  - python-pdal
  - python-dotenv
  - matplotlib
  - dask
  - distributed
  - ipykernel
  - ipython
  - ipython_genutils
  - jupyter_client
  - jupyter_core
  - spyder
  - spyder-kernels
  - pytest
  - geoapis >=0.3.0
  - pip:
    - netcdf4
    - osmpythontools >= 0.3.5

prefix: C:\ProgramData\Anaconda3\envs\geofabrics
