# YML file for setting up a virtual environment including packages used for processing point clouds, GIS and raster to produce raster using spyder.

name: geofabrics
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - dask
  - distributed
  - gdal
  - geopandas >=0.10.2
  - pdal >=2.3
  - pytest
  - python-dotenv
  - python-pdal
  - rioxarray
  - geoapis >=0.3.0
  - shapely >=2
  - pip:
    - netcdf4
    - osmpythontools >=0.3.5

prefix: C:\ProgramData\Anaconda3\envs\geofabrics
