# YML file for setting up a virtual environment including packages used for processing point clouds, GIS and raster to produce raster using spyder.

name: geofabrics
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - gdal
  - geopandas
  - rioxarray
  - pdal >=3.0
  - dask
  - distributed
  - python-pdal
  - python-dotenv
  - pytest
  - pip:
    - git+https://github.com/niwa/geoapis

prefix: C:\ProgramData\Anaconda3\envs\geofabrics
